In [1]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.


In [2]:
 import numpy as np

In [12]:
lst=list(range(10))

In [13]:
print(lst)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [14]:
print([i**2 for i in range(10)])

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [17]:
%timeit [i**2 for i in range(10)]

300 ns ± 8.47 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [18]:
arr=np.array(lst)

In [19]:
print(arr**2)

[ 0  1  4  9 16 25 36 49 64 81]


In [20]:
%timeit arr**2

202 ns ± 0.744 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## Numpy Basics


In [28]:
lst=list(range(10))

In [29]:
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
arr=np.array(lst)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
arr.ndim

1

In [32]:
arr.shape


(10,)

In [33]:
arr.size

10

In [34]:
lst=[[1,2,3],[4,5,6],[7,8,9]]

In [35]:
arr=np.array(lst)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr.size

9

In [38]:
arr.shape

(3, 3)

In [42]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [43]:
np.zeros((3,3),dtype='int')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [44]:
np.ones(shape=3)

array([1., 1., 1.])

In [45]:
np.ones(shape=(3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [48]:
np.ones(shape=(4,3),dtype="int")

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [53]:
np.diag((1,2,3,4)).astype('float')

array([[1., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 3., 0.],
       [0., 0., 0., 4.]])

In [55]:
np.identity(3,dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### Indexing in array

In [65]:
#one way to generate random numbers
import random
random.randint(0,10)


2

In [75]:
#2nd way using numpy
arr=np.random.randint(0,100,size=(5,6))

In [76]:
arr

array([[85, 46, 92, 13, 76, 60],
       [73, 14, 79, 14, 33, 32],
       [80, 76, 73, 22, 94, 72],
       [99, 24, 24, 52, 80, 16],
       [ 6, 15, 42, 38, 38,  9]])

In [77]:
arr[0][0]

85

In [78]:
arr[0]

array([85, 46, 92, 13, 76, 60])

In [80]:
arr[0,0]

85

In [81]:
arr[-1,-1]

9

In [82]:
len(arr)

5

### Array Slicing

In [83]:
arr

array([[85, 46, 92, 13, 76, 60],
       [73, 14, 79, 14, 33, 32],
       [80, 76, 73, 22, 94, 72],
       [99, 24, 24, 52, 80, 16],
       [ 6, 15, 42, 38, 38,  9]])

`arr[rows,cols]`

`arr[rows : rows + 1, cols : cols + 1]`

In [87]:
arr[2:5,2:5]

array([[73, 22, 94],
       [24, 52, 80],
       [42, 38, 38]])

In [88]:
arr[2:4,:]

array([[80, 76, 73, 22, 94, 72],
       [99, 24, 24, 52, 80, 16]])

### Boolean Masking

In [90]:
bool_mask=arr>50

In [91]:
print(bool_mask)

[[ True False  True False  True  True]
 [ True False  True False False False]
 [ True  True  True False  True  True]
 [ True False False  True  True False]
 [False False False False False False]]


In [92]:
sum(bool_mask)

array([4, 1, 3, 1, 3, 2])

In [93]:
bool_mask.sum()

14

In [94]:
arr[bool_mask]

array([85, 92, 76, 60, 73, 79, 80, 76, 73, 94, 72, 99, 52, 80])

In [95]:
arr[arr>50]

array([85, 92, 76, 60, 73, 79, 80, 76, 73, 94, 72, 99, 52, 80])

In [96]:
arr==1

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

### Numpy Operations

In [132]:
a=np.array([2,4])
b=np.array([5,8])

In [98]:
a

array([2, 4])

In [99]:
a+b

array([ 7, 12])

In [100]:
a-b

array([-3, -4])

In [101]:
a*b

array([10, 32])

In [102]:
a/b

array([0.4, 0.5])

In [103]:
a*2

array([4, 8])

In [106]:
np.log2(2)

1.0

In [108]:
np.log2(a)

array([1., 2.])

### Matrix Operations

In [131]:
A=np.random.randint(1,5,size=(3,5))
B=np.random.randint(1,5,size=(5,4))

In [111]:
a

array([[2, 4, 3, 4, 3],
       [1, 1, 2, 1, 4],
       [2, 4, 3, 3, 4]])

In [112]:
b

array([[4, 1, 1, 4],
       [1, 4, 1, 2],
       [3, 3, 2, 2],
       [1, 4, 4, 1],
       [4, 2, 3, 1]])

In [114]:
np.dot(a,b)

array([[37, 49, 37, 29],
       [28, 23, 22, 15],
       [40, 47, 36, 29]])

In [115]:
a@b

array([[37, 49, 37, 29],
       [28, 23, 22, 15],
       [40, 47, 36, 29]])

In [116]:
np.matmul(a,b)

array([[37, 49, 37, 29],
       [28, 23, 22, 15],
       [40, 47, 36, 29]])

In [119]:
np.matrix(a)

matrix([[2, 4, 3, 4, 3],
        [1, 1, 2, 1, 4],
        [2, 4, 3, 3, 4]])

### MIsc Operations

In [124]:
np.reshape(a,(15,1))

array([[2],
       [4],
       [3],
       [4],
       [3],
       [1],
       [1],
       [2],
       [1],
       [4],
       [2],
       [4],
       [3],
       [3],
       [4]])

In [125]:
np.reshape(a,(1,15))

array([[2, 4, 3, 4, 3, 1, 1, 2, 1, 4, 2, 4, 3, 3, 4]])

In [127]:
vec=np.arange(0,16)

In [130]:
np.reshape(vec,(4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [133]:
np.sqrt(A)

array([[2.        , 1.        , 1.73205081, 2.        , 2.        ],
       [1.        , 1.41421356, 1.73205081, 1.        , 1.73205081],
       [1.        , 2.        , 2.        , 2.        , 1.41421356]])

In [134]:
np.square(A)

array([[16,  1,  9, 16, 16],
       [ 1,  4,  9,  1,  9],
       [ 1, 16, 16, 16,  4]])

In [135]:
A

array([[4, 1, 3, 4, 4],
       [1, 2, 3, 1, 3],
       [1, 4, 4, 4, 2]])

In [136]:
np.sum(B)

52

In [140]:
B

array([[2, 1, 4, 3],
       [1, 1, 3, 4],
       [3, 4, 4, 4],
       [1, 1, 4, 3],
       [2, 3, 3, 1]])

In [141]:
np.sum(B,axis=0)

array([ 9, 10, 18, 15])

In [142]:
A

array([[4, 1, 3, 4, 4],
       [1, 2, 3, 1, 3],
       [1, 4, 4, 4, 2]])

In [143]:
B

array([[2, 1, 4, 3],
       [1, 1, 3, 4],
       [3, 4, 4, 4],
       [1, 1, 4, 3],
       [2, 3, 3, 1]])

In [144]:
np.transpose(B)

array([[2, 1, 3, 1, 2],
       [1, 1, 4, 1, 3],
       [4, 3, 4, 4, 3],
       [3, 4, 4, 3, 1]])

In [145]:
B.T

array([[2, 1, 3, 1, 2],
       [1, 1, 4, 1, 3],
       [4, 3, 4, 4, 3],
       [3, 4, 4, 3, 1]])

In [147]:
np.vstack((a,b))

array([[2, 4],
       [5, 8]])

In [172]:
a=np.arange(12).reshape(4,3)

In [173]:
a


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [174]:
b=np.arange(16).reshape(4,4)

In [175]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [176]:
np.hstack((a,b))

array([[ 0,  1,  2,  0,  1,  2,  3],
       [ 3,  4,  5,  4,  5,  6,  7],
       [ 6,  7,  8,  8,  9, 10, 11],
       [ 9, 10, 11, 12, 13, 14, 15]])

### Broadcasting

In [177]:
A

array([[4, 1, 3, 4, 4],
       [1, 2, 3, 1, 3],
       [1, 4, 4, 4, 2]])

In [178]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [179]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [180]:
b1=np.array([1,2,3])

In [181]:
b1.shape

(3,)

In [182]:
a.shape

(4, 3)

In [183]:
a+b1

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11],
       [10, 12, 14]])

In [189]:
b1=np.array([[1,2,3,4]])

In [190]:
b1.shape

(1, 4)

In [191]:
a+b1.T

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15]])

In [192]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

### Vectorization

In [193]:
a=np.array([2,4])
b=np.array([3,5])

In [194]:
d=0.0

for i in range(2):
    d+=(a[i]-b[i])**2

print(d**0.5)

1.4142135623730951


In [195]:
np.sqrt(np.sum((a-b)**2))

1.4142135623730951

### Practice Question

In [1]:
import numpy as np
y=[4,10,15,9,3,12]
y_tilda=[8,11,14,12,1,10]

In [5]:
def mse(y,yhat):
    
    y=np.array(y)
    yhat=np.array(yhat)
    
    return np.sum((y-yhat)**2)/y.size

In [6]:
mse(y,y_tilda)

5.833333333333333